module.exports = {
    app: require('./app'),
    auth: require('./auth'),
    config: require('./config'),
    controller: require('./controller'),
    dotenv: require('./dotenv'),
    folder: require('./folder'),
    locale: require('./locale'),
    logger: require('./logger'),
    program: require('./program'),
    router: require('./router'),
    secret: require('./secret'),
    string: require('./string'),
    view: require('./view'),
}